pytorch_lightning_pruning_callback:
  _target_: optuna.integration.PyTorchLightningPruningCallback
  trial: null # Cannot be accessed with sweeper currently =>> https://github.com/facebookresearch/hydra/issues/1710
  monitor: "val_loss"