model:
  _target_: darts.models.forecasting.block_rnn_model.BlockRNNModel
  input_chunk_length : 64
  output_chunk_length : 14
  model : "RNN"
  hidden_dim : 47
  n_rnn_layers : 4
  batch_size: 30
  n_epochs: 20
  dropout: 0.2999267470430375
  force_reset: True
  save_checkpoints: False
  random_state: 42
