model:
  _target_: darts.models.forecasting.nbeats.NBEATSModel
  input_chunk_length : 64
  output_chunk_length : 14
  num_stacks: 30
  num_blocks: 1
  num_layers: 4
  layer_widths: 256
  expansion_coefficient_dim: 5
  trend_polynomial_degree: 2
  dropout: 0.0
  activation: 'ReLU'
  force_reset: True 
  save_checkpoints: False
